# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

books = Book.create([{title: 'The Safety of Objects'}, 
                    {title: "Einstein's Dreams"}, 
                    {title: 'Cry The Beloved Country'}, 
                    {title: '44 Scotland Street'}, 
                    {title: 'The Count of Monte Cristo'}, 
                    {title: "Endurance: Shackleton's Incredible Voyage"}, 
                    {title: 'Le Petit Prince', summary: "In the original French or English, this whimisical book reminds you about what it's like to be a child. If you had a rocketship, a flower, and an invisible sheep."}, 
                    {title: 'A Walk In The Woods'}, 
                    {title: 'Jessica'}, 
                    {title: 'Jane Eyre', summary: "The original romance novel, with the implied scandalous relationships and fake weddings."}, 
                    {title: 'The Scapegoat'}, 
                    {title: 'Me Talk Pretty One Day', summary: "Only for people who enjoy stories of Paris, midgets, and Jesus."}, 
                    {title: 'Homer & Langley'}, 
                    {title: "Who's Afraid of Virginia Wolfe?"}, 
                    {title: "The Night Circus", summary: "A magical battle between two forces that takes place in a fantastic circus. Quite possibly the best book written in 2012."}, 
                    {title: "Great Gatsby"}, 
                    {title: "Souless", summary: "Yet another steampunk novel, although this one features an old maid who happens to be preternatural."}, 
                    {title: "Game of Thrones", summary: "As great as the HBO series is, the book is that much better."}, 
                    {title: "The Sign of the Seahorse"}, 
                    {title: "Wicked", summary: "The political scene of Oz before Dorothy comes to town."}, 
                    {title: "To Kill a Mockingbird"}, 
                    {title: "The Turn of the Screw"}, 
                    {title: "Harry Potter and the Sorcerer's Stone", summary: "Wizards. An orphan. An overwhelmingly evil villan who can't smell."}, 
                    {title: "On the Road"}, 
                    {title: "The Gospel According to Larry"}, 
                    {title: "The Eyre Affair", summary: "Alternate realities where travel into books is not only a reality but a necessity, with semi-obscure literary references around every corner."}, 
                    {title: "My Sister's Keeper"}, 
                    {title: "Midnight in the Garden of Good and Evil"}, 
                    {title: "A Prayer for Owen Meany"}, 
                    {title: "Gulliver's Travels"}, 
                    {title: "Los Alamos"}, 
                    {title: "Fall of Giants"}, 
                    {title: "Speak"}, 
                    {title: "Stiff: The Curious Lives of Human Cadavers"}, 
                    {title: "I Know Why The Caged Bird Sings"}, 
                    {title: "Looking for Alibrandi"}, 
                    {title: "Timeline"}, 
                    {title: "The Unbearable Lightness of Being"}, 
                    {title: "Stardust"}, 
                    {title: "Stardust"}, 
                    {title: "How To Be Good"}, 
                    {title: "Life and Death in Shanghai"}, 
                    {title: "The Virginian"}, 
                    {title: "The Monkey Wrench"}, 
                    {title: "Fahrenheit 451", summary: "Reality tv is the king, and firemen start fires with books. In other words, the world in about 5 years."}, 
                    {title: "Early Autumn"}, 
                    {title: "Joseph Anton"}, 
                    {title: "The Dark is Rising"}, 
                    {title: "The Bell Jar"}, 
                    {title: "The Return of the Native"}, 
                    {title: "The Things They Carried"}, 
                    {title: "Their Eyes Were Watching God"}, 
                    {title: "Enchanted, Inc.", summary: "Magic really esists, and those strange people you see in NYC are actually fairies and gnomes and other magical beings. Oh yeah, and the main character is totally immune and needs to fight the epic battle of good and evil."}])
authors = Author.create([{ first_name: 'Chicago', last_name: },
     { first_name: 'Chicago', last_name: },
     { first_name: 'Chicago', last_name: },
     { first_name: 'Chicago', last_name: },
     { first_name: 'Chicago', last_name: },
     { first_name: 'Chicago', last_name: },
     { first_name: 'Chicago', last_name: },
     { first_name: 'Chicago', last_name: },
     { first_name: 'Chicago', last_name: },
     { first_name: 'Chicago', last_name: },
     { first_name: 'Chicago', last_name: },
     { first_name: 'Chicago', last_name: },
     { first_name: 'Chicago', last_name: },
     { first_name: 'Chicago', last_name: },
     { first_name: 'Chicago', last_name: },
     { first_name: 'Chicago', last_name: },
     { first_name: 'Chicago', last_name: },
     { first_name: 'Chicago', last_name: },
     { first_name: 'Chicago', last_name: },
     { first_name: 'Chicago', last_name: },
     { first_name: 'Chicago', last_name: },
     { first_name: 'Chicago', last_name: },
     { first_name: 'Chicago', last_name: },
     { first_name: 'Chicago', last_name: },
     { first_name: 'Chicago', last_name: },
     { first_name: 'Chicago', last_name: },
     { first_name: 'Chicago', last_name: },
     { first_name: 'Chicago', last_name: },
     { first_name: 'Chicago', last_name: },
     { first_name: 'Chicago', last_name: },
     { first_name: 'Chicago', last_name: },
     { first_name: 'Chicago', last_name: },
     { first_name: 'Chicago', last_name: },
     { first_name: 'Chicago', last_name: },
     { first_name: 'Chicago', last_name: },
     { first_name: 'Chicago', last_name: },
     { first_name: 'Chicago', last_name: },
     { first_name: 'Chicago', last_name: },
     { first_name: 'Chicago', last_name: },
     { first_name: 'Chicago', last_name: },
     { first_name: 'Chicago', last_name: },
     { first_name: 'Chicago', last_name: },
     { first_name: 'Chicago', last_name: },
     { first_name: 'Chicago', last_name: },
     { first_name: 'Chicago', last_name: },
     { first_name: 'Chicago', last_name: },
     { first_name: 'Chicago', last_name: },
     { first_name: 'Chicago', last_name: },
     { first_name: 'Chicago', last_name: },
     { first_name: 'Chicago', last_name: },
     { first_name: 'Chicago', last_name: },
     { first_name: 'Chicago', last_name: },
     { first_name: 'Chicago', last_name: },